meta_product_name: "Fonts in the Wild"
meta_title: "Fonts in the Wild - Quickly find the perfect free & paid fonts for your next project"
meta_description: "Quickly find quality free & paid fonts for your next project"
meta_image: "metaimg.png"
twitter_account: "@meghanxmartin"
